name: yolcu360_kahve
description: powered by mahmuthanb
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  dio: any
  encrypt: ^5.0.3
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.4.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.4
  image_picker: ^1.0.4
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.1
  package_info_plus: ^5.0.1
  pretty_dio_logger: ^1.3.1
  restart_app: ^1.2.1
  retrofit: ^4.0.3
  route_map: ^0.0.17
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  launcher_icon:
    git: https://github.com/emintolgahanpolat/launcher_icon.git
  retrofit_generator: ^8.0.6
  route_map_generator: ^0.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/sora/
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/sora/Sora-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sora/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/sora/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sora/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/sora/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/sora/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/sora/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sora/Sora-Thin.ttf
          weight: 100

flutter_gen:
  output: lib/core/res
  assets:
    outputs:
      class_name: AppAssets
  colors:
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors.xml
